### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by geekedtv** [r7wx/easy-gate#1]
Found you! :)

Any plans for a dark mode? Also what other feature are planned?

**Comment by r7wx** [comment]
Sure, dark mode or even full theme customization will be released in the next version. For now no other functionality features are planned, since the main goal is to keep the application as simple and minimal as possible, but if you have any proposals feel free to ask.

**Comment by geekedtv** [comment]
Awesome! I shared the project on reddit here. https://www.reddit.com/r/selfhosted/comments/ugs179/easygate_a_gate_to_your_self_hosted_infrastructure/

**Comment by r7wx** [comment]
Thanks for sharing, new release is out now with theme customization [b5e81c2](https://github.com/r7wx/easy-gate/commit/b5e81c2775ee88e4b3a90c924ec19aef2c6a4829).
