### ISSUE TITLE
Failure to Launch

### ISSUE THREAD

**Issue by MeCJay12** [r7wx/easy-gate#15]
Hello! I think I'm overlooking something basic. I use the following docker run command to launch Easy Gate and the following JSON file but no matter what, Easy Gate just shows a loading icon. I tried starting Easy Gate without mounting a config file and it starts but then I can't figure out how to view files in the container (bash, ash, sh, and cat all fail). I also tried varying levels in the JSON file. below is the most basic. I also tried with groups and services stanzas. 

```
docker run -d \
	--restart always \
	--network better_bridge \
	--name=EasyGate \
	-v /mnt/Docker/EasyGate/easy-gate.json:/etc/easy-gate/easy-gate.json \
	r7wx/easy-gate
```

```
{
  "addr": "0.0.0.0:8080",
  "behind_proxy": true,
  "title": "Easy Gate",
  "icon": "fa-solid fa-cubes",
  "motd": "Welcome to Easy Gate",
  "theme": {
    "background": "#FFFFFF",
    "foreground": "#000000"
  }
}
```

**Comment by r7wx** [comment]
The reason you see a loading page is because the api reply with status code 400: See https://github.com/r7wx/easy-gate/issues/12. You have configured Easy Gate to run behind an already configured reverse proxy, but you are not providing the "X-Forwarded-For" header correctly.

**Comment by MeCJay12** [comment]
Sorry, forgot to include Nginx config. I have the recommended configs in Nginx. 

```
server {
        listen 443 ssl;

        server_name easy.domain.com;

        ssl_certificate /etc/nginx/ssl/live/easy.domain.com/fullchain.pem;
        ssl_certificate_key /etc/nginx/ssl/live/easy.domain.com/privkey.pem;
        include /etc/nginx/ssl/options-ssl-nginx.conf;
        ssl_dhparam /etc/nginx/ssl/ssl-dhparams.pem;

        location / {
                proxy_pass http://EasyGate.:8080;
                proxy_set_header X-Forward-For $proxy_add_x_forwarded_for;
        }
}
```

**Comment by r7wx** [comment]
Try to change the header to  "X-Forwarded-For":

```
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
```

In your configuration I see "X-Forward-For"

**Comment by MeCJay12** [comment]
Yup, that worked. Thanks for the quick response. I see now that the container logs show the successful connection. Could I recommend a log for an unsuccessful connection?

**Comment by r7wx** [comment]
Glad to hear! Yes logging should definitely be improved, I will close this issue and track the log issue in this one: https://github.com/r7wx/easy-gate/issues/16
