### ISSUE TITLE
Add options to change the String in Services and Notes

### ISSUE THREAD

**Issue by LeoColman** [r7wx/easy-gate#18]
https://github.com/r7wx/easy-gate/blob/44e280390e7d97541b53f89f6729a2bf29f3548d/web/src/App.js#L90

https://github.com/r7wx/easy-gate/blob/44e280390e7d97541b53f89f6729a2bf29f3548d/web/src/App.js#L102

**Comment by r7wx** [comment]
Yep I will remove them in the next release and maybe introduce a category feature in future releases (each item can be assigned to a category)

**Comment by r7wx** [comment]
Solved in release 1.1.3.
