### ISSUE TITLE
[Feature Request] IP Adress related redirecting

### ISSUE THREAD

**Issue by Pheggas** [r7wx/easy-gate#2]
Hey. I'm pretty sure this has to be edge case that wouldn't use many users but i have ZeroTier set up for accessing my services from outside of local network. I'm really annoyed when i need to manually rewrite IP and port of the service because i'm not on the local network. 

Example:
My zerotier ip: 192.168.192.10
My server's zerotier ip: 192.168.192.15 (and in local network it is 192.168.1.15)

I have configured inside Easy Gate local IP of that service (192.168.1.15:9000). But i'm accessing it from outside the network via zerotier so when i click the button, it want to load the 192.168.1.15:9000 instead of 192.168.192:9000.

# **Solution**

Add option to make redirection based on IP that is connected to Easy Gate.

**Comment by r7wx** [comment]
If I did understand your issue correctly, what are you trying to accomplish is the main feature of Easy Gate itself.
You can define two groups and two copy of the same service (with different group):

```json
"groups": [
  {
    "name": "internal",
    "subnet": "192.168.1.1/24"  // ENTER YOUR LOCAL NET SUBNET
  },
  {
    "name": "vpn",
    "subnet": "192.168.192.1/24"  // ENTER YOUR VPN SUBNET
  }
]
```

And for services:

```json
{
  "icon": "fa-solid fa-cube",
  "name": "Your service",
  "url": "https:/192.168.1.15", // IP OF THE SERVICE ON LOCAL NETWORK
  "groups": [
      "internal" // THIS IS FOR LOCAL NETWORK USERS
  ]
},
{
  "icon": "fa-solid fa-cube",
  "name": "Your service",
  "url": "https://192.168.192.15",  // IP OF THE SERVICE ON VPN NETWORK
  "groups": [
       "vpn"      // THIS IS FOR VPN USERS
   ]
}
```
With this configuration you will hopefully see only the correct entry based on your connection IP address.

Let me know if this could work for you

**Comment by Pheggas** [comment]
From what i see in code you provided, it looks really promissing. Unfortunately, i just started complete rework of my homelab so i'll let you know in couple of days.
