### ISSUE TITLE
Is there a way to embed html in a note?

### ISSUE THREAD

**Issue by DoubleWookie** [r7wx/easy-gate#21]
The title pretty much says it all, is there a way to embed an iframe into a note, or replace a note with such a thing? If not, that might be a cool feature to add if it is not too complex or would bloat the code.

Love the project and the style btw!

**Comment by r7wx** [comment]
Hello, thank you for the interest!
Sadly this feature is not on plan due to potential security issues.
If you have a specific feature in mind maybe there are other ways around

**Comment by DoubleWookie** [comment]
That's all good, i was just wondering,
i prefer a secure setup over funky feature that's causing security issues
