### ISSUE TITLE
armv7 compatibility

### ISSUE THREAD

**Issue by rubenixnagios** [r7wx/easy-gate#3]
any chance to make this armv7 compatible?

nice work

**Comment by r7wx** [comment]
Thank you, I just update the docker-hub image, now it should be multi-arch and correctly working on arm64.
Unfortunately I am not able to test it on real hardware anytime soon, so can you please test if it's all working correctly?

**Comment by rubenixnagios** [comment]
can test on armv7 (32bits system) dont have a 64bit ssystem to try it out.
will be available on 32 bit systems?

thanks

**Comment by r7wx** [comment]
Opps, ok I updated it again currently targeting the following platforms:
```
linux/amd64, linux/arm/v7, linux/arm64/v8
```
If it still does not work for you, you can try to clone the whole repository and execute docker-compose build on your production machine.

**Comment by rubenixnagios** [comment]
allright, will let you know as soon as I try it; nice job man!!

**Comment by rubenixnagios** [comment]
working flawlessly on debian buster armv7!
