### ISSUE TITLE
Custom CSS

### ISSUE THREAD

**Issue by nothing-fr** [r7wx/easy-gate#32]
Are there any plans for a custom CSS system? (loading external stylesheet for overrides, etc...)

This would allow more advanced customization of elements (note colors, service colors, etc.)

![image](https://github.com/r7wx/easy-gate/assets/92157590/4fddc828-4e3a-4f50-9f35-61fffcd46c3b)

Thanks !

**Comment by Unknown1309** [comment]
I am a beginner learning the JSON structure, and I would like to ask about the code to separate 'services' on a single page, for example, the titles 'IT-Tools and their websites' and 'HR-Tools and their websites.
Example:
![268241624-4fddc828-4e3a-4f50-9f35-61fffcd46c3b](https://github.com/r7wx/easy-gate/assets/152018349/4a335fbb-cc77-4828-973a-869e58e9add0)
My final question, is there a way to add the website logo at the top of the page?

Thank you very much!

**Comment by dzonerzy** [comment]
I made a PR https://github.com/r7wx/easy-gate/pull/35 let see if gets approved

**Comment by r7wx** [comment]
The PR is approved and merged into dev branch, the feature will be available in the next release! Thank you!

**Comment by r7wx** [comment]
Feature available on release 2.0.1
