### ISSUE TITLE
Easy-Gate docker container style.css 404 not found when running behind nginx reverse proxy in a subfolder / subpath

### ISSUE THREAD

**Issue by etescartz** [r7wx/easy-gate#37]
Easy-Gate looks like something I could use and wanted to give it a try. I am using a nginx reverse proxy and followed the mentioned confiuration:

```
[...]
"behind_proxy": true,
[...]
```

I first noticed that the page style was only showing basic html content after starting the easygate containter using the [lastest docker image](https://hub.docker.com/r/r7wx/easy-gate/tags).

I also use this in my easy-gate nginx config file.
```[...]
location / {
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_pass http://easy-gate:8080;
}
[...]
```

I initially thought there was a file location or path I missed and started going through the container's file system looking for a `style.css` file and didn't find any.

Then I started looking at the `Dockerfile` and thought I would try to build an image locally but ran into GO proxy authentication issues with some of the go dependencies ( for `github.com/klauspost/compress` the docker build command said `access denied` which after a short web search I found out is related to the specific go proxy being used) 

This opened a whole new can of worms for me since I don't have a go environment set up on my machine and I'm not looking to pursue that.

Please let me know if I'm missing some important easy-gate configuration detail.
At first glance I would think that the `style.css` file is not built into the easy-gate docker image. I'm not a go developer and I may be mistaken, so if there's any way that you could make [these static files](https://github.com/r7wx/easy-gate/tree/master/internal/engine/static/public) available in the docker image I would be grateful.

**Comment by etescartz** [comment]
Thanks for writing back! 

I just want the standard builtin `style.css` file.

I think I'm missing something in my nginx reverse proxy config.
I tried to force Nginx to forward all requests to the Go app, including static assets like this:

```
server {
    listen 443 ssl;

    server_name  nas.local;

    location /easy-gate/ {
        proxy_pass http://easy-gate:8080/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
```

But the Nginx logs still show that it's trying to load `style.css`, `favicon.ico` from the Nginx container, not from the `easy-gate` docker container:
```
10.0.0.124 - - [14/Oct/2024:17:29:20 +0000] "GET /easy-gate/ HTTP/1.1" 200 6870 "-"
2024/10/14 17:29:20 [error] 21#21: *1 open() "/usr/share/nginx/html/style.css" failed (2: No such file or directory), client: 10.0.0.124, server: _, request: "GET /style.css HTTP/1.1", host: "nas.local", referrer: "https://nas.local/easy-gate/"
10.0.0.124 - - [14/Oct/2024:17:29:20 +0000] "GET /style.css HTTP/1.1" 404 153 "https://nas.local/easy-gate/"

```

Just for reference, here is the content of my easy-gate.yml configuration file which I'm enforcing using `-e EASY_GATE_CONFIG_PATH=/etc/easy-gate/easy-gate.yml`

```
addr: 0.0.0.0:8080
use_tls: false
cert_file: ""
key_file: ""
behind_proxy: true
title: Easy Gate
theme:
  background: "#000000"
  foreground: "#FFFFFF"
groups:
  - name: internal
    subnet: 10.0.0.0/24
services:
  - name: Forgejo
    category: "Code"
    url: https://nas.local/forgejo/
    groups:
      - internal
```
This custom easy gate works because I can see it in the browser but like said, it's just basic html.

I'll keep trying looking for nginx config options that might fix this for me.

**Comment by etescartz** [comment]
I managed to get Nginx to pass everything to the `easy-gate` docker container by specifically routing requests for the `style.css`, `favicon.ico` and `roboto-regular.ttf` files to `easy-gate:8080`

```
server {
    listen 443 ssl;

    server_name  nas.local;

    location /easy-gate/ {
        rewrite ^/easy-gate(/.*)$ $1 break;
        proxy_pass http://easy-gate:8080;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
    location /style.css {
        proxy_pass http://easy-gate:8080/style.css;
    }
    location /favicon.ico {
        proxy_pass http://easy-gate:8080/favicon.ico;
    }
    location /roboto-regular.ttf {
        proxy_pass http://easy-gate:8080/roboto-regular.ttf;
    }

    }
}
```
Now I can see CSS:

![image](https://github.com/user-attachments/assets/f0f8f0de-d4f1-4570-9821-241ef0e90df0)

Would it be possible to make `easy-gate` handle requests when running in a subfolder or subpath, behind a reverse proxy?

**Comment by r7wx** [comment]
I was about to write the same thing 😄 
You are correct the problem is the subpath "easy-gate", I need to push a fix to be able to specify a root folder for the application.

**Comment by etescartz** [comment]
Works like a charm! Thanks for implementing this!
