### ISSUE TITLE
Custom Icons

### ISSUE THREAD

**Issue by bdunn44** [r7wx/easy-gate#9]
Love the simplicity of this!

At risk of asking for more complexity and breaking a core principle of this project, would you consider adding the ability to use arbitrary images as icons? Either by URL or loaded from a local assets folder. Font Awesome is great but I've quickly found myself wanting to embed custom icons (like TP Link's icon for network portals, Traefik's icon for that dashboard, etc., etc.)

**Comment by r7wx** [comment]
Thank you, I will take in consideration the custom icon feature if I will find a way to fit it in the project without compromising the simplicity of it. At the moment I do not think that loading from url/asset folder would be the best fit.

**Comment by r7wx** [comment]
Custom icons are now available in release v1.2.0
